vich_uploader:
    db_driver: orm

    mappings:
        program_file:
            uri_prefix: '%app_upload_directory%/program'
            upload_destination: '%app_path_upload_directory%/program'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
